config/routes.rb
Rails.application.routes.draw do
  resources :user_activities
  get '/about', to: "home#about"
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user_activity.rb
class UserActivity < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @name = "Test"
  end

  def about
  end
end

app/controllers/user_activities_controller.rb
class UserActivitiesController < ApplicationController
  before_action :set_user_activity, only: [:show, :edit, :update, :destroy]

  # GET /user_activities
  # GET /user_activities.json
  def index
    @user_activities = UserActivity.all
  end

  # GET /user_activities/1
  # GET /user_activities/1.json
  def show
  end

  # GET /user_activities/new
  def new
    @user_activity = UserActivity.new
  end

  # GET /user_activities/1/edit
  def edit
  end

  # POST /user_activities
  # POST /user_activities.json
  def create
    @user_activity = UserActivity.new(user_activity_params)

    respond_to do |format|
      if @user_activity.save
        format.html { redirect_to @user_activity, notice: 'User activity was successfully created.' }
        format.json { render :show, status: :created, location: @user_activity }
      else
        format.html { render :new }
        format.json { render json: @user_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_activities/1
  # PATCH/PUT /user_activities/1.json
  def update
    respond_to do |format|
      if @user_activity.update(user_activity_params)
        format.html { redirect_to @user_activity, notice: 'User activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_activity }
      else
        format.html { render :edit }
        format.json { render json: @user_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_activities/1
  # DELETE /user_activities/1.json
  def destroy
    @user_activity.destroy
    respond_to do |format|
      format.html { redirect_to user_activities_url, notice: 'User activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_activity
      @user_activity = UserActivity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_activity_params
      params.require(:user_activity).permit(:user_id, :activity_id, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_activities_helper.rb
module UserActivitiesHelper
end

app/views/home/about.html.erb
<%= link_to "Home", :root %>
<%= link_to "Home", "/" %>
<%= link_to "Home", root_path %>
<%= link_to "Home", root_url %>
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<%= 1 + 1%>
<div class="something <%= "special-class" %>">
<%= Time.now%>
</div>

Hello <%= @name%>!!!

<%= link_to "About", "/about" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <%= link_to :user_activities, :user_activities%>
    <%= yield %>
  </body>
</html>

app/views/user_activities/_form.html.erb
<%= form_with(model: user_activity, local: true) do |form| %>
  <% if user_activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_activity.errors.count, "error") %> prohibited this user_activity from being saved:</h2>

      <ul>
      <% user_activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :activity_id %>
    <%= form.number_field :activity_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_activities/edit.html.erb
<h1>Editing User Activity</h1>

<%= render 'form', user_activity: @user_activity %>

<%= link_to 'Show', @user_activity %> |
<%= link_to 'Back', user_activities_path %>

app/views/user_activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Activities</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Activity</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_activities.each do |user_activity| %>
      <tr>
        <td><%= user_activity.user_id %></td>
        <td><%= user_activity.activity_id %></td>
        <td><%= user_activity.status %></td>
        <td><%= link_to 'Show', user_activity %></td>
        <td><%= link_to 'Edit', edit_user_activity_path(user_activity) %></td>
        <td><%= link_to 'Destroy', user_activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Activity', new_user_activity_path %>

app/views/user_activities/new.html.erb
<h1>New User Activity</h1>

<%= render 'form', user_activity: @user_activity %>

<%= link_to 'Back', user_activities_path %>

app/views/user_activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_activity.user_id %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @user_activity.activity_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user_activity.status %>
</p>

<%= link_to 'Edit', edit_user_activity_path(@user_activity) %> |
<%= link_to 'Back', user_activities_path %>